# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e1c5e246106bcbc823c0e4c99c924a621d571ae8419d073099b465daa3cafe7d0331b854d7bfdc3fcb23d69f672e91d8119a34ab69493a16a40d3482fedf92b

test:
  secret_key_base: d5c143ab0ea56a3937688b63ede4d84e94deefb5d43467b74b2ebf303f1715e01c4aa2d047c695465833c9a8a63f6ae0980ea4a877708d04c5df07881f86e527

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
